version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Amsterdam
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-cli
    versions:
    - "> 3.14.0"
  - dependency-name: ember-data
    versions:
    - "> 3.14.0"
  - dependency-name: ember-source
    versions:
    - "> 3.14.2"
  - dependency-name: eslint-plugin-ember-suave
    versions:
    - "> 1.0.0"
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.25.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
    - 5.3.2
    - 5.4.0
    - 5.6.0
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-power-select
    versions:
    - 4.1.0
    - 4.1.2
    - 4.1.3
  - dependency-name: ember-concurrency
    versions:
    - 1.3.0
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: ember-cli-string-helpers
    versions:
    - 5.0.0
  - dependency-name: jquery
    versions:
    - 3.5.1
