---
language: node_js
node_js:
  - "5.0"

sudo: true
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default PERCY_ENABLE=1
  - EMBER_TRY_SCENARIO=ember-release PERCY_ENABLE=0
  - EMBER_TRY_SCENARIO=ember-beta PERCY_ENABLE=0
  - EMBER_TRY_SCENARIO=ember-canary PERCY_ENABLE=0

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
